version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.0

    working_directory: ~/repo

    environment:
      DB_URL: "mongodb://localhost:27017"
      DB_NAME: "mongodb"
      TOKEN: "faketoken"
      CODACY_PROJECT_TOKEN: "456ebbe09ea543de998aa9ce0890d14a"

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}-
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m flake8 . --exclude=.git,__pycache__,venv
            coverage run --source=code/source -m pytest
            coverage report -m
            coverage xml
            python-codacy-coverage -r coverage.xml
workflows:
  version: 2
  stack:
    jobs:
      - build
